name: Practice

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Resolve dep
        run: npm install

      - name: Build
        run: |
          cd frontend/
          npm install
          cd ..
          cd backend
          npm install
          cd ..

      - name: Deploy Changes
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ~/
          remote_host: 54.227.124.173
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}
    
    
  second-job: 
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: 54.227.124.173
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: sudo docker compose up
     
        
