name: Practice

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Resolve dep
        run: npm install

      - name: Build
        run: |
          cd frontend/
          npm install
          cd ..
          cd backend
          npm install
          cd ..

      - name: Start
        uses: fifsky/ssh-action@master
        with:
          command: ls
          host: 54.147.134.119
          user: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}


      - name: Deploy 
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./
          remote_path: ~/
          remote_host: 54.147.134.119
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: leave
        run: |
          exit
          pwd
        
