name: Practice

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Resolve dep
        run: npm i

      - name: Build
        run: |
          cd frontend/
          npm install
          cd ..
          cd backend
          npm install
          cd ..

      - name: Test
        run: |
          cypress install
          npm run test:frontend:unit
          npm run test:api:with:servers
          npm run test:frontend:with:server

      - name: Deploy 
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./
          remote_path: ~/
          remote_host: 54.144.103.38
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Start
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: 54.144.103.38
          username: ubuntu
          password: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo docker-compose up
        
