name: Practice

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Resolve dep
        run: npm install

      - name: Build
        run: |
          cd frontend/
          npm install
          cd ..
          cd backend
          npm install
          cd ..

      - name: Deploy 
        uses: contention/rsync-deployments@v2.0.0
        with:
          FLAGS: -avzr --delete
          EXCLUDES: --exclude .htaccess --exclude /uploads/
          USER: ubuntu
          HOST: 54.147.134.119
          LOCALPATH: ./
          REMOTEPATH: ~/
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Start
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: 54.147.134.119
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd ~/
            sudo docker-compose up

      - name: leave
        run: |
          exit
          pwd
        
